# Generated by Django 5.0.4 on 2024-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_sender_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='to_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='created_at',
        ),
    ]
